version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: gateway-1358
    volumes:
      - ./:/var/www:cached
    container_name: gateway-1358-app
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - my-network
    deploy:

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9002:9002"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9002"
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    networks:
      - my-network

  nginx:
    image: nginx:alpine
    container_name: gateway-1358-nginx
    restart: unless-stopped
    ports:
      - 82:80
    volumes:
      - ./docker-compose/nginx:/etc/nginx/conf.d:ro
      - ./:/var/www:ro
    networks:
      - my-network
 
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: database
      MYSQL_USER: duongdqt
      MYSQL_PASSWORD: database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network

volumes:
  db_data: 
  minio_data:

networks:
  my-network: